### ISSUE TITLE
Problem with CUDA

### ISSUE THREAD

**Issue by SjoerdTilburgUniversity** [SigCGANs/Conditional-Sig-Wasserstein-GANs#11]
Hi, I am a student and would like to use your code for research purposes, but I can't get the code to work.

When running "%run train.py -use_cuda -total_steps 1000" I get an error: "AssertionError: Torch not compiled with CUDA enabled". Also when running without cuda: "%run train.py -total_steps 1000" I get the same error. 

I installed the packages from requirements.yml in a conda environment.

**Comment by Baoren1996** [comment]
Hi, sorry for hear that you have problem when running the code, would you like to provide more detailed informaiton about the error message? It seems to me that your torch version is not compiled with CUDA.

**Comment by SjoerdTilburgUniversity** [comment]
Thank you! The packages that are installed in the environment are: 
packages in environment at C:\ProgramData\anaconda3\envs\siglib2:
#
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.1                       cpu_0  
asttokens                 2.4.0              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl    conda-forge
ca-certificates           2023.08.22           haa95532_0  
certifi                   2023.7.22        py38haa95532_0  
cffi                      1.14.0           py38ha419a9e_0    conda-forge
chardet                   3.0.4           py38h9bdc248_1008    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cryptography              2.9.2            py38hba49e27_0    conda-forge
cudatoolkit               10.0.130            he4282a3_12    conda-forge
cycler                    0.10.0                     py_2    conda-forge
debugpy                   1.8.0            py38hd3f51b4_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.2.9                h39d44d4_3    conda-forge
fontconfig                2.13.1            h2c6e35d_1000    conda-forge
freetype                  2.9.1             h563cfd7_1006    conda-forge
icc_rt                    2022.1.0             h6049295_2  
icu                       58.2                 ha925a31_3  
idna                      2.9                        py_1    conda-forge
intel-openmp              2020.1                      216  
ipykernel                 6.11.0           py38h4317176_0    conda-forge
ipython                   8.12.2             pyh08f2357_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
joblib                    0.15.1                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2  
jupyter_client            7.2.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.4.0            py38haa244fe_0    conda-forge
kiwisolver                1.2.0            py38h95a2b95_1    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libiconv                  1.15              hfa6e2cd_1006    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.1.0                h56a325e_0  
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.9                h9ce36c8_5    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
lz4                       4.3.2            py38hb6d8784_1    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.1.3                    py38_0    conda-forge
matplotlib-base           3.1.3            py38h2981e6d_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2020.1                      216  
mkl-service               2.3.0            py38h196d8e1_0  
mkl_fft                   1.0.15           py38h14836fe_0  
mkl_random                1.1.1            py38he6e81aa_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
ninja                     1.9.0                h1ad3211_1    conda-forge
numpy                     1.18.1           py38ha749109_1    conda-forge
numpy-base                1.18.1           py38hc3f5095_1  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1w               h2bbff1b_0  
pandas                    1.0.3            py38he6e81aa_1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    7.1.2            py38hcc1f983_0  
pip                       20.0.2                     py_2    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5            py38h91455d4_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyhd8ed1ab_1    conda-forge
pyqt                      5.9.2            py38hd77b12b_6  
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.8.3           cpython_h5fd99cc_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.4.0           cpu_py38ha775e86_0  
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywin32                   306              py38hd3f51b4_2    conda-forge
pyzmq                     25.1.1           py38hdecc13b_2    conda-forge
qt                        5.9.7            vc14h73c81de_0  
requests                  2.23.0             pyh8c360ce_2    conda-forge
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.4.0           py38h32f6830_0    conda-forge
signatory                 1.2.1.1.4.0              pypi_0    pypi
sip                       4.19.13          py38hd77b12b_0  
six                       1.14.0                     py_1    conda-forge
sqlite                    3.31.1               h2a8f88b_1  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.8             hfa6e2cd_1000    conda-forge
tornado                   6.0.4            py38h1e8a9f7_2    conda-forge
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
traitlets                 5.11.2             pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.25.8           py38h32f6830_1    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wcwidth                   0.2.8              pyhd8ed1ab_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wincertstore              0.2             pyhd8ed1ab_1009    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.5                h63175ca_0    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.3.7             haafe652_1001    conda-forge

The comes from:
`File [c:\ProgramData\anaconda3\envs\siglib2\lib\site-packages\torch\cuda\__init__.py:94](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:94), in _check_driver()
     [92](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:92) def _check_driver():
     [93](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:93)     if not hasattr(torch._C, '_cuda_isDriverSufficient'):
---> [94](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:94)         raise AssertionError("Torch not compiled with CUDA enabled")
     [95](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:95)     if not torch._C._cuda_isDriverSufficient():
     [96](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:96)         if torch._C._cuda_getDriverVersion() == 0:
     [97](file:///C:/ProgramData/anaconda3/envs/siglib2/lib/site-packages/torch/cuda/__init__.py:97)             # found no NVIDIA driver on the system

AssertionError: Torch not compiled with CUDA enabled`

**Comment by Baoren1996** [comment]
Hi, I can see that your current pytorch is CPU version, please follow the official instructions to install a cuda version [PyTorch ](https://pytorch.org/get-started/locally/), and make sure you installed the CUDA correctly [link](https://stackoverflow.com/questions/57814535/assertionerror-torch-not-compiled-with-cuda-enabled-in-spite-upgrading-to-cud).

**Comment by SjoerdTilburgUniversity** [comment]
Thanks for the reply! 

I downgraded my cuda to 9.2 such that it will run with with torch==1.4.0 and torchvision==0.5.0. It is now able to use cuda! 

However, the error I am getting now is the following:

{
	"name": "RuntimeError",
	"message": "CUDA error: invalid device ordinal",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~\\Documents\\SchoolTillie\\Master\\Thesis\\Conditional-Sig-Wasserstein-GANs\\train.py:162
    159 parser.add_argument('-total_steps', default=1000, type=int)
    161 args = parser.parse_args()
--> 162 main(args)

File ~\\Documents\\SchoolTillie\\Master\\Thesis\\Conditional-Sig-Wasserstein-GANs\\train.py:129, in main(args)
    127 generator = get_dataset_configuration(dataset)
    128 for spec, data_params in generator:
--> 129     run(
    130         algo_id=algo_id,
    131         base_config=base_config,
    132         data_params=data_params,
    133         dataset=dataset,
    134         base_dir=args.base_dir,
    135         spec=spec,
    136     )

File ~\\Documents\\SchoolTillie\\Master\\Thesis\\Conditional-Sig-Wasserstein-GANs\\train.py:54, in run(algo_id, base_config, base_dir, dataset, spec, data_params)
     52 # initialise dataset and algo
     53 x_real = get_data(dataset, base_config.p, base_config.q, **data_params)
---> 54 x_real = x_real.to(base_config.device)
     55 ind_train = int(x_real.shape[0] * 0.8)
     56 x_real_train, x_real_test = x_real[:ind_train], x_real[ind_train:] #train_test_split(x_real, train_size = 0.8)

RuntimeError: CUDA error: invalid device ordinal"
}

Any suggestions on how to fix this?

**Comment by Baoren1996** [comment]
> Thanks for the reply!
> 
> I downgraded my cuda to 9.2 such that it will run with with torch==1.4.0 and torchvision==0.5.0. It is now able to use cuda!
> 
> However, the error I am getting now is the following:
> 
> { "name": "RuntimeError", "message": "CUDA error: invalid device ordinal", "stack": "--------------------------------------------------------------------------- RuntimeError Traceback (most recent call last) File ~\Documents\SchoolTillie\Master\Thesis\Conditional-Sig-Wasserstein-GANs\train.py:162 159 parser.add_argument('-total_steps', default=1000, type=int) 161 args = parser.parse_args() --> 162 main(args)
> 
> File ~\Documents\SchoolTillie\Master\Thesis\Conditional-Sig-Wasserstein-GANs\train.py:129, in main(args) 127 generator = get_dataset_configuration(dataset) 128 for spec, data_params in generator: --> 129 run( 130 algo_id=algo_id, 131 base_config=base_config, 132 data_params=data_params, 133 dataset=dataset, 134 base_dir=args.base_dir, 135 spec=spec, 136 )
> 
> File ~\Documents\SchoolTillie\Master\Thesis\Conditional-Sig-Wasserstein-GANs\train.py:54, in run(algo_id, base_config, base_dir, dataset, spec, data_params) 52 # initialise dataset and algo 53 x_real = get_data(dataset, base_config.p, base_config.q, **data_params) ---> 54 x_real = x_real.to(base_config.device) 55 ind_train = int(x_real.shape[0] * 0.8) 56 x_real_train, x_real_test = x_real[:ind_train], x_real[ind_train:] #train_test_split(x_real, train_size = 0.8)
> 
> RuntimeError: CUDA error: invalid device ordinal" }
> 
> Any suggestions on how to fix this?

Hi RuntimeError: CUDA error: invalid device ordinal simply means the cuda device is not specified correctly, could you try 'cuda' 'cuda:0' or other options.
